<!-- Search Widget -->
<div class="card my-4">
  <h5 class="card-header">
    Buscar
  </h5>
  <div class="card-body">
    <form method="post" action="resultBusqueda.php">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Buscar por..." name="buscar" id="buscar" />
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="submit" title="search">
            Ir!
          </button>
        </span>
      </div>
    </form>
  </div>
</div>
<!-- /Search Widget -->
