<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">
      Copyright &copy; Your Website 2018
    </p>
  </div>
  <!-- /.container -->
</footer>
<!-- Bootstrap core JavaScript -->
<script src="js/jquery.min.js">
</script>
<script src="bootstrap/js/bootstrap.bundle.min.js">
</script>
<script type="text/javascript" src="js/jquery.validate.min.js">
</script>
<script type="text/javascript" src="js/interface.js">
</script>
<script type="text/javascript" src="js/jquery.colorbox-min.js">
</script>
<script type="text/javascript" src="js/forms.js">
</script>
<!-- Google Analytics -->
<script type="text/javascript" src="js/google-analytics.js">
</script>
<!-- End Google Analytics -->
<!-- /Footer -->
<?php
  $funciones->desconectar($link);
?>